sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=mgrstools
  - secure: ysTjTiPxAlXFnyYHv43XQGOvK4EyAxzxEe3XBmMfMrvK+DGmL1e7No1w4jQ4enXWWi/nwr5kYuQlSDSPOnO/5CwZxx11H+Qe9aRcg2qKegXNiWrSWrVAkfa+xvq8NVUO0VzNn3ZZ8YIJu/Su7DxHV9f5WGi4dvZvjI/fxJp3dDg=
  - secure: WSjmuT8OKyXd2QJIaffDmxYDQwqIipiRTyD3xX1s4J/sHnLILXwrwNNSoG6Q9AFgblbmgsKTRfkbkf2uk0KQIX0A8nbMHaG54WuMAdhJ7IRcwZwBRV7FHlAOEjAgyRYstknAN8l90QAJuXNyyBUBge3WWKcAiOKZrzFeTzf7l3s=
  matrix:
  - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
before_install:
- docker pull elpaso/qgis-testing-environment:${QGIS_VERSION_TAG}
- docker tag elpaso/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
- sleep 10
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker exec -it qgis-testing-environment sh -c "$PIP_EXECUTABLE install paver"
script:
- docker exec -it qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
- docker exec -it qgis-testing-environment sh -c "echo '${PLUGIN_NAME} has no unit tests yet, please create them and add here'"
notifications:
  slack:
    secure: ui1aBjelCtu9stZwoKunOV5pQ01Won63AN4fOvG1Z00duX52H4vDbPJqLWTpOFkhmDpEiDO78k0au2F9a6UeuhC5tJ/k8/5JgMkDXakaueGb5TgaWTb4DctOXAexUe8OyZ7Vw9wyy/Ek7o9nYs0WznwTnDZ+o7IxjH8Th/DDK9o=
after_success:
- |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
        mkdir /home/travis/.ssh/
        chmod 700 /home/travis/.ssh/
        openssl aes-256-cbc -K $encrypted_5fbe6ce81355_key -iv $encrypted_5fbe6ce81355_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
        tar xzvf travis_secrets.tar.gz
        mv id_rsa.qgisrepoguest /home/travis/.ssh/id_rsa.qgisrepoguest
        mv ssh_config /home/travis/.ssh/config
        chmod 600 /home/travis/.ssh/id_rsa.qgisrepoguest
        chmod 600 /home/travis/.ssh/config
        export RELEASE_ZIPNAME=${PLUGIN_NAME}.zip
        echo "Uploading ${RELEASE_ZIPNAME} to QGIS Dev..."
        scp ${PLUGIN_NAME}.zip qgisrepoguest:${UPLOADS}/${RELEASE_ZIPNAME}
        export GIT_REV=$(git rev-parse --short HEAD)
        ssh qgisrepoguest "${UPDATER} update --remove-version all --role desktop-qgis-plugin-dev --git-hash ${GIT_REV} qgis-dev ${RELEASE_ZIPNAME}"
    fi
